"""Regression tests for the four v0.5.2 bootstrap-pipeline bugs.

Bug 1 — atomic_profile_commit clobbers `.chameleon/.skip` + sibling files
    The transaction's dir-rename replaces the entire `.chameleon/` tree on
    every bootstrap. Committed sibling files (`.skip`, `.gitignore`,
    `.editorconfig`, hand-authored `.notes`) silently disappear on each
    refresh — defeating `.skip` as a team-shared opt-out. v0.5.2 copies
    non-protocol siblings into the txn_dir BEFORE the rename so they
    survive. Protocol files (profile.json, idioms.md, …) the writer
    emitted always win over a sibling-copy of the same name.

Bug 2 — Rails-aware naming priors in naming.py
    forem reported 5/7 archetypes as `cluster-<hex>` fallbacks even though
    the codebase had clear Rails patterns. v0.5.2 adds a Rails-prior table
    (`app/models/`, `app/services/`, `app/jobs/`, `app/mailers/`,
    `app/helpers/`, `app/policies/`, `app/serializers/`,
    `app/presenters/`, `app/workers/`, `app/views/`, `db/migrate/`,
    `app/controllers/concerns/`, …) that fires only when the cluster's
    canonical witness is a `.rb` file. Filename-suffix discriminators
    (`_job.rb`, `_mailer.rb`, `_helper.rb`) anchor against rogue files.

Bug 3 — `paths_pattern` drops `models/` prefix on some Rails archetypes
    `path_pattern_bucket_for("app/models/rule/action_executor/foo.rb")`
    yields `app/rule/action_executor` — the load-bearing `models/`
    segment is missing. Touching the bucket key would break runtime
    archetype lookup (it's the same string both writers use), so v0.5.2
    keeps `paths_pattern` byte-identical to the bucket and adds a
    sibling `paths_pattern_display` field carrying the witness-honest
    form. profile.summary.md prefers the display field so reviewers
    aren't misled.

Bug 4 — `db/schema.rb` always reported as "added" on partial-refresh
    Discovery's pre-bootstrap walk picked up `db/schema.rb` because the
    `.rb` glob matched, but the clustering layer dropped it (single-
    member generic cluster). Every refresh saw `db/schema.rb` in the
    candidate list but not in `prev_state`, so it counted as "added",
    pushed change-count > 0, and forced a full bootstrap. v0.5.2 adds
    `db/schema.rb` and `db/structure.sql` to the discovery exclusion
    set since they're Rails-autogenerated and clustering them is
    meaningless.

Run:
    cd mcp && PYTHONPATH=.:../tests .venv/bin/python ../tests/v0_5_2_bootstrap_test.py
"""

from __future__ import annotations

import json
import os
import shutil
import sys
import tempfile
from pathlib import Path

# Make the in-repo chameleon_mcp importable without installing.
HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parent.parent / "mcp"))


# Isolate plugin data so trust grants we make below don't leak.
TMPDATA = tempfile.mkdtemp(prefix="chameleon_v052_bootstrap_data_")
os.environ["CHAMELEON_PLUGIN_DATA"] = TMPDATA


PASS = 0
FAIL = 0


def t(label: str, cond: bool, detail: str = "") -> None:
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  [PASS] {label}")
    else:
        FAIL += 1
        print(f"  [FAIL] {label}" + (f" — {detail}" if detail else ""))


def section(name: str) -> None:
    print(f"\n=== {name} ===")


from chameleon_mcp.bootstrap.discovery import (  # noqa: E402
    EXCLUDE_FROM_CLUSTERING_EXACT_RELPATHS,
    discover_files,
)
from chameleon_mcp.bootstrap.naming import (  # noqa: E402
    _is_ruby_cluster,
    _rails_prior_match,
    propose_archetype_name,
)
from chameleon_mcp.bootstrap.orchestrator import (  # noqa: E402
    _displayed_paths_pattern,
    bootstrap_repo as _orchestrator_bootstrap,
)
from chameleon_mcp.bootstrap.transaction import (  # noqa: E402
    COMMITTED_SENTINEL,
    _PROTOCOL_FILES,
    atomic_profile_commit,
)


# ---------------------------------------------------------------------------
# Bug 1 — atomic_profile_commit preserves sibling files
# ---------------------------------------------------------------------------
section("Bug 1 — sibling files survive atomic_profile_commit")

# Set up an existing .chameleon/ directory with both protocol files and the
# user-committed sibling files that should survive a re-bootstrap.
bug1_root = Path(tempfile.mkdtemp(prefix="chameleon_v052_bug1_"))
profile_dir = bug1_root / ".chameleon"
profile_dir.mkdir()

# Protocol-owned files (will be re-emitted by the writer).
(profile_dir / "COMMITTED").write_text("committed-at=1.0\npid=1\n")
(profile_dir / "profile.json").write_text(json.dumps({"schema_version": 7}))
(profile_dir / "idioms.md").write_text("# idioms\n## active\noriginal idiom\n")

# User-authored siblings — these MUST survive.
(profile_dir / ".skip").write_text("team opt-out — chameleon disabled\n")
(profile_dir / ".gitignore").write_text(".tmp/\n*.bak\n")
(profile_dir / ".editorconfig").write_text("[*]\nindent_size = 2\n")
(profile_dir / ".notes").write_text("hand-written team notes about chameleon\n")

# Write through atomic_profile_commit; only protocol files are emitted.
with atomic_profile_commit(profile_dir) as txn_dir:
    (txn_dir / "profile.json").write_text(json.dumps({"schema_version": 7}))
    (txn_dir / "archetypes.json").write_text(json.dumps({"archetypes": {}}))
    (txn_dir / "canonicals.json").write_text(json.dumps({"canonicals": {}}))
    (txn_dir / "rules.json").write_text(json.dumps({"rules": {}}))
    (txn_dir / "idioms.md").write_text("# idioms\n## active\nNEW idiom\n")
    (txn_dir / "profile.summary.md").write_text("# summary\n")

# Verify siblings survived.
t(
    ".skip survives atomic_profile_commit",
    (profile_dir / ".skip").is_file(),
    f"contents={(profile_dir / '.skip').read_text() if (profile_dir / '.skip').is_file() else 'MISSING'!r}",
)
t(
    ".skip contents are byte-identical to the original",
    (profile_dir / ".skip").read_text() == "team opt-out — chameleon disabled\n",
)
t(
    ".gitignore survives atomic_profile_commit",
    (profile_dir / ".gitignore").is_file(),
)
t(
    ".gitignore contents preserved",
    (profile_dir / ".gitignore").read_text() == ".tmp/\n*.bak\n",
)
t(
    ".editorconfig survives atomic_profile_commit",
    (profile_dir / ".editorconfig").is_file(),
)
t(
    "arbitrary `.notes` sibling survives",
    (profile_dir / ".notes").is_file()
    and "hand-written team notes" in (profile_dir / ".notes").read_text(),
)

# Verify the writer's new idioms.md beat the sibling-preservation path (the
# protocol file in txn_dir wins).
t(
    "writer's new idioms.md replaces the old one (txn wins over sibling)",
    "NEW idiom" in (profile_dir / "idioms.md").read_text()
    and "original idiom" not in (profile_dir / "idioms.md").read_text(),
)

# Sanity: the protocol-file set is exhaustive of what the writer emits.
expected_protocol = {
    "COMMITTED",
    "profile.json",
    "archetypes.json",
    "canonicals.json",
    "rules.json",
    "idioms.md",
    "profile.summary.md",
    "renames.json",
}
t(
    "protocol-file set matches the writer's emit list",
    _PROTOCOL_FILES == expected_protocol,
    f"got {_PROTOCOL_FILES!r}",
)
t(
    "COMMITTED constant matches the protocol set entry",
    COMMITTED_SENTINEL in _PROTOCOL_FILES,
)

# Sanity: COMMITTED sentinel is present (atomic_profile_commit always
# writes it last).
t(
    "COMMITTED sentinel written by the new txn",
    (profile_dir / "COMMITTED").is_file(),
)

shutil.rmtree(bug1_root, ignore_errors=True)


# Edge case: nested subdir as a sibling (e.g., the team committed a
# `.chameleon/notes/` directory). Should be preserved as a tree, not flattened.
section("Bug 1 — nested sibling directories preserved")

bug1b_root = Path(tempfile.mkdtemp(prefix="chameleon_v052_bug1b_"))
profile_dir = bug1b_root / ".chameleon"
profile_dir.mkdir()
nested = profile_dir / "team-notes"
nested.mkdir()
(nested / "README.md").write_text("# team notes\nthis is checked in\n")
(nested / "design.md").write_text("design doc\n")

with atomic_profile_commit(profile_dir) as txn_dir:
    (txn_dir / "profile.json").write_text("{}")
    (txn_dir / "idioms.md").write_text("# idioms\n")

t(
    "nested team-notes/ directory survives",
    (profile_dir / "team-notes").is_dir(),
)
t(
    "files inside the nested directory survive byte-identical",
    (profile_dir / "team-notes" / "README.md").is_file()
    and "this is checked in" in (profile_dir / "team-notes" / "README.md").read_text(),
)
t(
    "second file inside the nested directory survives",
    (profile_dir / "team-notes" / "design.md").is_file(),
)

shutil.rmtree(bug1b_root, ignore_errors=True)


# Edge case: empty target dir (first-ever bootstrap). Must not blow up
# when there's nothing to preserve.
section("Bug 1 — first-time bootstrap (no pre-existing target_dir)")

bug1c_root = Path(tempfile.mkdtemp(prefix="chameleon_v052_bug1c_"))
profile_dir = bug1c_root / ".chameleon"  # does NOT exist yet
with atomic_profile_commit(profile_dir) as txn_dir:
    (txn_dir / "profile.json").write_text("{}")
    (txn_dir / "idioms.md").write_text("# fresh\n")

t(
    "first-time bootstrap creates the profile dir cleanly",
    (profile_dir / "profile.json").is_file()
    and (profile_dir / "COMMITTED").is_file(),
)

shutil.rmtree(bug1c_root, ignore_errors=True)


# ---------------------------------------------------------------------------
# Bug 2 — Rails-aware naming priors
# ---------------------------------------------------------------------------
section("Bug 2 — Rails-prior table is keyed on the canonical Ruby dirs")

from dataclasses import dataclass, field as dc_field  # noqa: E402


@dataclass
class _FakeKey:
    path_pattern_bucket: str = ""
    default_export_kind: str | None = None
    top_level_node_kinds: tuple[str, ...] = ()
    jsx_present: bool = False


@dataclass
class _FakeMember:
    path: Path


@dataclass
class _FakeCluster:
    key: _FakeKey
    members: list[_FakeMember] = dc_field(default_factory=list)
    cluster_id: str = "f00dcafef00dcafe"


def cluster(
    *,
    bucket: str,
    members: list[str],
    default_export: str | None = "ClassNode",
    top_level_kinds: tuple[str, ...] = ("ClassNode",),
    jsx: bool = False,
) -> _FakeCluster:
    return _FakeCluster(
        key=_FakeKey(
            path_pattern_bucket=bucket,
            default_export_kind=default_export,
            top_level_node_kinds=top_level_kinds,
            jsx_present=jsx,
        ),
        members=[_FakeMember(path=Path(p)) for p in members],
    )


# Run the heuristic over each Rails-conventional archetype directory and
# verify the priors emit the canonical name. The bucket passed in is the
# v5 signature bucket — the heuristic relies on the member paths, not the
# bucket, for Rails detection (since v5 collapses inner segments).
RAILS_CASES = [
    # (display_label, bucket, members, expected_name)
    ("app/models/ → model", "app/models", ["app/models/user.rb", "app/models/order.rb"], "model"),
    ("app/services/ → service", "app/services", ["app/services/users/create.rb", "app/services/orders/update.rb"], "service"),
    ("app/jobs/<*>_job.rb → job", "app/jobs", ["app/jobs/email_job.rb", "app/jobs/cleanup_job.rb"], "job"),
    ("app/mailers/<*>_mailer.rb → mailer", "app/mailers", ["app/mailers/user_mailer.rb", "app/mailers/order_mailer.rb"], "mailer"),
    ("app/helpers/<*>_helper.rb → helper", "app/helpers", ["app/helpers/application_helper.rb", "app/helpers/users_helper.rb"], "helper"),
    ("db/migrate/ → migration", "db/migrate", ["db/migrate/20240101_create_users.rb", "db/migrate/20240102_add_email.rb"], "migration"),
    ("app/controllers/concerns/ → controller-concern", "app/controllers/concerns", ["app/controllers/concerns/authenticatable.rb", "app/controllers/concerns/loggable.rb"], "controller-concern"),
    ("app/policies/ → policy", "app/policies", ["app/policies/user_policy.rb", "app/policies/order_policy.rb"], "policy"),
    ("app/serializers/ → serializer", "app/serializers", ["app/serializers/user_serializer.rb", "app/serializers/order_serializer.rb"], "serializer"),
    ("app/presenters/ → presenter", "app/presenters", ["app/presenters/user_presenter.rb", "app/presenters/order_presenter.rb"], "presenter"),
    ("app/workers/ → worker", "app/workers", ["app/workers/sidekiq_worker.rb", "app/workers/cleanup_worker.rb"], "worker"),
    ("app/views/ → view", "app/views", ["app/views/users/index.html.erb.rb", "app/views/orders/show.html.erb.rb"], "view"),
    ("app/controllers/ → controller", "app/controllers", ["app/controllers/users_controller.rb", "app/controllers/orders_controller.rb"], "controller"),
]
for label, bucket_, members_, expected in RAILS_CASES:
    name = propose_archetype_name(
        cluster(bucket=bucket_, members=members_),
        existing_names=set(),
    )
    t(label, name == expected, f"got {name!r}")


# A non-Ruby cluster MUST NOT engage the Rails-prior path. The TS-side
# token heuristic may still produce a familiar name for a TS file under
# `app/models/` (back-compat), but it never goes through _rails_prior_match.
# Verify the prior-match function itself short-circuits on a non-Ruby
# cluster — that's the contract the brief specifies.
match = _rails_prior_match(["app/models/types.ts", "app/models/schemas.ts"])
# _rails_prior_match doesn't itself check language (it's the caller's job),
# so it WILL match on directory-chain alone. The language gate lives in
# _is_ruby_cluster, which is called BEFORE _rails_prior_match in
# _base_name_for. Verify both halves of the gate.
t(
    "_is_ruby_cluster blocks TS clusters from the Rails-prior path",
    _is_ruby_cluster(["app/models/types.ts", "app/models/schemas.ts"]) is False,
)
# _rails_prior_match, when called on Ruby-shaped paths, returns the
# matching name — verify the function works in isolation too.
match_ruby = _rails_prior_match(["app/models/user.rb", "app/models/order.rb"])
t(
    "_rails_prior_match returns 'model' on Ruby members",
    match_ruby == "model",
    f"got {match_ruby!r}",
)


# _is_ruby_cluster is a small but load-bearing helper; sanity-check it.
t(
    "_is_ruby_cluster True for .rb members",
    _is_ruby_cluster(["app/services/foo.rb", "app/services/bar.rb"]) is True,
)
t(
    "_is_ruby_cluster False for .ts members",
    _is_ruby_cluster(["app/services/foo.ts"]) is False,
)
t(
    "_is_ruby_cluster False for empty input",
    _is_ruby_cluster([]) is False,
)

# Filename-suffix discrimination: a _job.rb under a non-jobs dir doesn't
# auto-become a job; the directory chain has the final say.
match = _rails_prior_match(["lib/random/email_job.rb", "lib/random/cleanup_job.rb"])
t(
    "_job.rb outside app/jobs/ does NOT match the job prior",
    match is None,
    f"got {match!r}",
)


# ---------------------------------------------------------------------------
# Bug 3 — paths_pattern_display surfaces the witness-honest form
# ---------------------------------------------------------------------------
section("Bug 3 — _displayed_paths_pattern repairs collapsed Rails buckets")

# The canonical failure mode from the maybe dogfood:
#   bucket = "app/rule/action_executor"
#   witness = "app/models/rule/action_executor/auto_categorize.rb"
#   expected display = "app/models/action_executor"
display = _displayed_paths_pattern(
    "app/rule/action_executor",
    "app/models/rule/action_executor/auto_categorize.rb",
)
t(
    "maybe-style buggy bucket → app/models/action_executor",
    display == "app/models/action_executor",
    f"got {display!r}",
)

# Deep namespace under app/controllers/ — the collapsed bucket loses
# `controllers/`; display must restore it.
display = _displayed_paths_pattern(
    "app/admin/dashboards",
    "app/controllers/admin/dashboards/foo.rb",
)
t(
    "app/controllers/<deep> witness → app/controllers/dashboards",
    display == "app/controllers/dashboards",
    f"got {display!r}",
)

# Bucket already contains the load-bearing segment — no change.
display = _displayed_paths_pattern(
    "app/models",
    "app/models/user.rb",
)
t(
    "bucket already correct (app/models) → unchanged",
    display == "app/models",
    f"got {display!r}",
)

# Short witness path (<4 parts) is unaffected — the v5 bucket can't have
# collapsed anything load-bearing.
display = _displayed_paths_pattern(
    "src/components",
    "src/components/Button.tsx",
)
t(
    "short non-Rails witness → bucket unchanged",
    display == "src/components",
    f"got {display!r}",
)

# Top-level segment NOT app/ — leave it alone (we don't want to over-
# correct on TS/Next.js layouts).
display = _displayed_paths_pattern(
    "src/foo/bar",
    "src/components/foo/bar/Card.tsx",
)
t(
    "non-app/ top-level → bucket unchanged",
    display == "src/foo/bar",
    f"got {display!r}",
)

# Empty witness (defensive) → fall back to bucket.
display = _displayed_paths_pattern("app/v1/users", "")
t(
    "empty witness → bucket unchanged",
    display == "app/v1/users",
)

# v0.5.2 (Bug 3): paths_pattern is byte-identical to the cluster bucket
# so runtime lookup (path_pattern_bucket_for == archetype.paths_pattern)
# still matches; the display lives separately.
# Verify that with a quick end-to-end probe.
section("Bug 3 — paths_pattern stays bucket-equivalent (lookup-compatible)")

bug3_root = Path(tempfile.mkdtemp(prefix="chameleon_v052_bug3_"))
# Hand-craft a Rails layout deep enough to trigger collapse.
(bug3_root / "Gemfile").write_text("source 'https://rubygems.org'\n")
(bug3_root / "config").mkdir()
(bug3_root / "config" / "application.rb").write_text("# Rails app\n")
# Conventional models/services dirs.
for rel in [
    "app/models/rule/action_executor/auto_categorize.rb",
    "app/models/rule/action_executor/manual_review.rb",
    "app/models/rule/action_executor/notify_owner.rb",
    "app/models/rule/action_executor/escalate.rb",
    "app/models/rule/action_executor/dismiss.rb",
    "app/services/users/create.rb",
    "app/services/users/update.rb",
    "app/services/users/destroy.rb",
    "app/services/users/list.rb",
    "app/services/users/show.rb",
]:
    fp = bug3_root / rel
    fp.parent.mkdir(parents=True, exist_ok=True)
    # Minimal valid Ruby class so prism_dump can parse it.
    fp.write_text(f"class {Path(rel).stem.title().replace('_', '')}\nend\n")

report = _orchestrator_bootstrap(bug3_root.resolve())
t(
    "Bug 3 synthetic Rails bootstrap succeeded",
    report.status == "success",
    f"got {report.status} ({report.error})",
)
# Inspect the emitted archetypes.json.
arch_path = bug3_root / ".chameleon" / "archetypes.json"
if arch_path.is_file():
    arch = json.loads(arch_path.read_text())
    has_display = any(
        "paths_pattern_display" in a for a in arch.get("archetypes", {}).values()
    )
    t(
        "at least one archetype has paths_pattern_display",
        has_display,
        f"archetypes={list(arch.get('archetypes', {}).keys())[:5]}...",
    )
    # The cluster bucket and the display string MAY differ — but never
    # equal each other when the display repair actually fired. Verify
    # that paths_pattern is bucket-shaped (no Rails repair) so runtime
    # lookup still keys correctly.
    bucket_matches_signature = True
    from chameleon_mcp.signatures import path_pattern_bucket_for
    canonicals_path = bug3_root / ".chameleon" / "canonicals.json"
    canonicals = json.loads(canonicals_path.read_text()).get("canonicals", {})
    for name, a in arch.get("archetypes", {}).items():
        witness_rels = canonicals.get(name) or []
        if not witness_rels:
            continue
        witness_rel = witness_rels[0]["witness"]["path"]
        expected_bucket = path_pattern_bucket_for(witness_rel)
        # Some signature versions append :ext; allow either form.
        if a["paths_pattern"] not in {expected_bucket, f"{expected_bucket}:rb"}:
            bucket_matches_signature = False
            print(f"    archetype {name}: stored={a['paths_pattern']!r}, computed={expected_bucket!r}")
            break
    t(
        "stored paths_pattern matches path_pattern_bucket_for(witness)",
        bucket_matches_signature,
    )
else:
    t("Bug 3 synthetic archetypes.json emitted", False, f"path={arch_path}")

shutil.rmtree(bug3_root, ignore_errors=True)


# ---------------------------------------------------------------------------
# Bug 4 — db/schema.rb excluded from discovery
# ---------------------------------------------------------------------------
section("Bug 4 — Rails autogenerated files excluded from discovery")

t(
    "db/schema.rb is in EXCLUDE_FROM_CLUSTERING_EXACT_RELPATHS",
    "db/schema.rb" in EXCLUDE_FROM_CLUSTERING_EXACT_RELPATHS,
)
t(
    "db/structure.sql is in EXCLUDE_FROM_CLUSTERING_EXACT_RELPATHS",
    "db/structure.sql" in EXCLUDE_FROM_CLUSTERING_EXACT_RELPATHS,
)

# Fixture repo: a single hand-authored model + the autogenerated schema.rb.
# Discovery must yield ONLY the hand-authored file.
bug4_root = Path(tempfile.mkdtemp(prefix="chameleon_v052_bug4_"))
(bug4_root / "Gemfile").write_text("source 'https://rubygems.org'\n")
(bug4_root / "app" / "models").mkdir(parents=True)
(bug4_root / "app" / "models" / "user.rb").write_text("class User\nend\n")
(bug4_root / "db").mkdir()
(bug4_root / "db" / "schema.rb").write_text(
    "ActiveRecord::Schema.define do\n  create_table 'users'\nend\n"
)
# Real Rails authored migration — should NOT be excluded.
(bug4_root / "db" / "migrate").mkdir()
(bug4_root / "db" / "migrate" / "20240101_create_users.rb").write_text(
    "class CreateUsers < ActiveRecord::Migration[7.0]\nend\n"
)

discovered = discover_files(bug4_root, glob="**/*.rb")
discovered_rels = {str(p.relative_to(bug4_root)) for p in discovered}

t(
    "db/schema.rb excluded from discovery",
    "db/schema.rb" not in discovered_rels,
    f"got {discovered_rels}",
)
t(
    "hand-authored model is still discovered",
    "app/models/user.rb" in discovered_rels,
)
t(
    "real migrations are still discovered",
    "db/migrate/20240101_create_users.rb" in discovered_rels,
)

# Add a db/structure.sql even though the glob is .rb — discovery's glob
# already filters by extension, so structure.sql wouldn't be discovered
# anyway. But the explicit-exclusion set protects against future
# language additions.
(bug4_root / "db" / "structure.sql").write_text("CREATE TABLE users();\n")
sql_discovered = discover_files(bug4_root, glob="**/*.sql")
sql_discovered_rels = {str(p.relative_to(bug4_root)) for p in sql_discovered}
t(
    "db/structure.sql excluded even when the glob matches",
    "db/structure.sql" not in sql_discovered_rels,
    f"got {sql_discovered_rels}",
)


# End-to-end: full bootstrap on the Bug 4 fixture must NOT include
# db/schema.rb in the candidate list (verified above) AND a re-bootstrap
# of the same tree must not produce different file_clusters counts.
report = _orchestrator_bootstrap(bug4_root.resolve())
t(
    "Bug 4 fixture bootstrap status=success",
    report.status == "success",
    f"got {report.status} ({report.error})",
)
# Re-bootstrap should be deterministic.
report2 = _orchestrator_bootstrap(bug4_root.resolve())
t(
    "Bug 4 fixture re-bootstrap status=success",
    report2.status == "success",
)
t(
    "files_processed deterministic across bootstraps",
    report.files_processed == report2.files_processed,
    f"first={report.files_processed} second={report2.files_processed}",
)

shutil.rmtree(bug4_root, ignore_errors=True)


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
section("Summary")
print(f"\n  Total: {PASS + FAIL}")
print(f"  Pass: {PASS}")
print(f"  Fail: {FAIL}")
sys.exit(1 if FAIL else 0)
