"""Cluster ParsedFile records by ClusterKey signature.

Per ARCHITECTURE.md "Cluster signature function" → "Incremental algorithm":
- Same ClusterKey → same cluster (exact-match equivalence)
- Clusters become candidate archetypes (named in Phase 2C interview)
- Sparse cluster threshold: <5 files → candidate for "miscellaneous" or merge
- Bimodal threshold: clusters split 60/40 or worse on a key dimension are flagged

Phase 2B implements the basic exact-match clustering; sparse + bimodal
detection deferred to Phase 2C.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from typing import Iterable

from chameleon_mcp.extractors._base import ParsedFile
from chameleon_mcp.signatures import ClusterKey, compute_signature

# Files in clusters smaller than this aren't proposed as their own archetype
# without explicit user confirmation.
SPARSE_CLUSTER_THRESHOLD = 5


@dataclass
class Cluster:
    """A group of files sharing a cluster signature."""

    key: ClusterKey
    members: list[ParsedFile] = field(default_factory=list)

    @property
    def size(self) -> int:
        return len(self.members)

    @property
    def is_sparse(self) -> bool:
        return self.size < SPARSE_CLUSTER_THRESHOLD


@dataclass
class ClusteringResult:
    """Output of clustering a parsed corpus."""

    clusters: list[Cluster]
    """All clusters, sorted by size descending (largest first)."""

    skipped_generated: list[ParsedFile] = field(default_factory=list)
    """Files identified as auto-generated by content heuristic; excluded from clustering."""

    @property
    def cluster_count(self) -> int:
        return len(self.clusters)

    @property
    def total_files_clustered(self) -> int:
        return sum(c.size for c in self.clusters)

    @property
    def sparse_clusters(self) -> list[Cluster]:
        return [c for c in self.clusters if c.is_sparse]

    @property
    def dense_clusters(self) -> list[Cluster]:
        return [c for c in self.clusters if not c.is_sparse]


def cluster_files(parsed_files: Iterable[ParsedFile]) -> ClusteringResult:
    """Group parsed files by ClusterKey signature.

    Args:
        parsed_files: iterable of successfully-parsed files (from
                      TypeScriptExtractor.parse_repo().files)

    Returns:
        ClusteringResult with clusters sorted by size (largest first) for
        deterministic archetype proposal ordering.
    """
    from chameleon_mcp.bootstrap.discovery import is_likely_generated

    by_key: dict[ClusterKey, list[ParsedFile]] = defaultdict(list)
    skipped_generated: list[ParsedFile] = []

    for pf in parsed_files:
        # Generated-code heuristic on file content head
        if is_likely_generated(pf.content_first_200_bytes):
            skipped_generated.append(pf)
            continue

        key = compute_signature(
            file_path=str(pf.path),
            content_first_200_bytes=pf.content_first_200_bytes,
            top_level_node_kinds=pf.top_level_node_kinds,
            default_export_kind=pf.default_export_kind,
            named_export_count=pf.named_export_count,
            import_specifiers=pf.import_specifiers,
            has_jsx=pf.has_jsx,
        )
        by_key[key].append(pf)

    clusters = [Cluster(key=k, members=members) for k, members in by_key.items()]
    clusters.sort(key=lambda c: c.size, reverse=True)

    return ClusteringResult(
        clusters=clusters,
        skipped_generated=skipped_generated,
    )
