"""File discovery for bootstrap.

Walks a repo, applies path-based exclusions, enforces the 50k post-glob
ceiling per Round 2 cost adversary recommendation.

Two exclusion sets:
1. EXCLUDE_FROM_CLUSTERING — paths never analyzed (vendor, build, generated)
2. EXCLUDE_FROM_CANONICAL_POOL — clustered but never picked as canonical
   (tests, legacy, archive, deprecated)

Per docs/architecture.md "Bootstrap interview flow" steps (e), (f).
"""

from __future__ import annotations

import fnmatch
import os
from pathlib import Path

# Hard ceiling on file count post-exclusion. Bootstrap refuses above this
# without explicit user-supplied paths_glob.
#
# v0.5.2: bumped 50_000 -> 100_000 (2x) after the gitlabhq dogfood (~125k
# files) bounded out at the prior cap.
# v0.5.3: bumped 100_000 -> 200_000 (4x baseline) after cycle-2 dogfood
# confirmed real-world Rails+JS monorepos (gitlabhq plus the GitLab
# enterprise tree) approach the 125k mark and other anticipated apps
# (Plane's full monorepo with all packages, Discourse, Forem-pro) sit
# in the 100k-200k band. Discovery is dominated by stat() + xxhash
# sha_hint; bootstrap wall-time on a 200k repo measured 3.5-4 minutes
# on the reference SSD which is acceptable for the one-shot install
# experience. The other 50_000 caps in tools.py guard user input shape
# (teach_profile body, structured payload) and are unrelated.
REPO_SIZE_GUARD = 200_000

# Directory NAMES that, if present anywhere in a file's path components,
# disqualify the file from clustering. Matched component-by-component, not
# as glob — this is more reliable than fnmatch globs for `**/x/**` semantics
# (fnmatch's `*` matches `/`, so `**/node_modules/**` doesn't anchor at root).
EXCLUDE_FROM_CLUSTERING_DIRS = frozenset({
    "node_modules",
    "vendor",
    "dist",
    "build",
    ".next",
    ".nuxt",
    ".turbo",
    ".cache",
    ".parcel-cache",
    "__generated__",
    "generated",
    ".git",
    "storage",
    "tmp",
    "coverage",
    ".coverage",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    ".venv",
    "venv",
    "__pycache__",
    ".idea",
    ".vscode",
    ".chameleon",  # never analyze our own profile dir
})

# Filename patterns to exclude (handle leaf-name globs separately).
EXCLUDE_FROM_CLUSTERING_FILE_GLOBS = (
    ".DS_Store",
    "*.min.js",
    "*.min.css",
    "*.bundle.js",
    "*.lock",
)

# v0.5.2 (Bug 4): exact-relative-path exclusions for autogenerated files
# the user never authors but discovery picks up because the extension
# matches.
#
# Rationale: ``db/schema.rb`` is Rails' autogenerated snapshot of
# ``ActiveRecord::Schema.define`` — its contents are regenerated by every
# ``rails db:migrate``, so clustering it is meaningless (it has its own
# AST shape that doesn't match anything the team writes by hand).
#
# Worse: discovery's pre-bootstrap walk *includes* ``db/schema.rb`` but
# the downstream ``file_clusters`` index drops it (the clustering layer
# rejects single-member generic clusters). On every refresh, the diff
# step in ``_attempt_partial_refresh`` sees ``db/schema.rb`` in the
# current candidate list but NOT in the persisted ``prev_state`` →
# reports it as ``"added"`` → change-count > 0 → partial refresh aborts
# and falls through to a full bootstrap. The forem and maybe dogfoods
# both hit this: every refresh, no matter how trivial, did a full
# bootstrap.
#
# ``db/structure.sql`` is the SQL-flavor equivalent under
# ``config.active_record.schema_format = :sql``; it has the same
# autogenerated-on-migrate property.
EXCLUDE_FROM_CLUSTERING_EXACT_RELPATHS = frozenset({
    "db/schema.rb",
    "db/structure.sql",
})

# Paths INCLUDED in clustering but EXCLUDED from canonical pool.
# Per docs/architecture.md: tests, legacy, archive directories shouldn't become
# the team's "this is how we do it" reference.
EXCLUDE_FROM_CANONICAL_POOL_PATTERNS = (
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/spec/**",
    "**/specs/**",
    "**/legacy/**",
    "**/archive/**",
    "**/_archive/**",
    "**/.archive/**",
    "**/deprecated/**",
    "**/*.test.*",
    "**/*.spec.*",
    "**/*.stories.*",
    "**/*.fixture.*",
    "**/cypress/**",
    "**/e2e/**",
    "**/.storybook/**",
)


class TooManyFilesError(Exception):
    """Raised when a repo exceeds REPO_SIZE_GUARD without explicit paths_glob."""

    def __init__(self, count: int, ceiling: int = REPO_SIZE_GUARD) -> None:
        self.count = count
        self.ceiling = ceiling
        super().__init__(
            f"repo has {count} files (ceiling {ceiling}); "
            "use explicit paths_glob to scope analysis"
        )


def _matches_any(rel_path: str, patterns: tuple[str, ...]) -> bool:
    """Return True if rel_path matches any fnmatch pattern.

    Use this for canonical-pool exclusions (where fnmatch semantics work).
    For directory-component matching, use _has_excluded_component instead.
    """
    return any(fnmatch.fnmatch(rel_path, pat) for pat in patterns)


def _has_excluded_component(rel_path: Path, excluded_dirs: frozenset[str]) -> bool:
    """True if any path component is in the excluded directory denylist."""
    return any(part in excluded_dirs for part in rel_path.parts)


def _matches_filename_glob(name: str, patterns: tuple[str, ...]) -> bool:
    """True if the bare filename matches any leaf-name glob."""
    return any(fnmatch.fnmatch(name, pat) for pat in patterns)


def _glob_candidates(
    repo_root: Path,
    target_glob: str,
    *,
    workspace_roots: list[str] | None = None,
) -> list[Path]:
    """Run the brace-expansion glob against ``repo_root`` (and optional
    workspace sub-roots) and return the union of matched paths.

    Used by both ``discover_files`` and ``discovery_stats`` so the
    pre-exclusion counter and the post-exclusion list always agree on
    what the walker saw.
    """
    bases: list[Path]
    if workspace_roots:
        bases = [(repo_root / ws).resolve() for ws in workspace_roots]
    else:
        bases = [repo_root]

    candidates: list[Path] = []
    seen: set[Path] = set()
    for base in bases:
        if not base.is_dir():
            continue
        if "{" in target_glob and "}" in target_glob:
            prefix, _, rest = target_glob.partition("{")
            body, _, suffix = rest.partition("}")
            alts = [a.strip() for a in body.split(",")]
            for alt in alts:
                for p in base.glob(f"{prefix}{alt}{suffix}"):
                    if p not in seen:
                        seen.add(p)
                        candidates.append(p)
        else:
            for p in base.glob(target_glob):
                if p not in seen:
                    seen.add(p)
                    candidates.append(p)
    return candidates


def discovery_stats(
    repo_root: Path,
    *,
    glob: str = "**/*.{ts,tsx,js,jsx,mjs,cjs}",
    paths_glob: str | None = None,
    workspace_roots: list[str] | None = None,
) -> dict[str, int]:
    """Return pre- and post-exclusion file counts without raising.

    v0.5.3 (Bug D): instrumentation helper for bootstrap_repo so callers
    can report coverage (how many files were discovered, how many made
    it past the exclusion sets, how many were clustered) without
    re-walking the tree multiple times in different layers.

    Unlike ``discover_files`` this never raises ``TooManyFilesError`` —
    coverage telemetry on an oversized repo is still useful diagnostics.

    Counter semantics (post-rec-13):
    - Symlinks and non-regular files are dropped before either counter
      increments — they are never eligible for clustering, so counting
      them would overstate the discoverable surface.
    - ``pre_exclusion`` counts files that survive the symlink + is_file
      gate but before the EXCLUDE_FROM_CLUSTERING_* sets are applied.
    - ``post_exclusion`` counts files that survive both gates.

    Hardlinks are not detected — that requires same-filesystem write
    access to the repo, which the threat model already assumes a
    trusted user has. The symlink filter targets the cross-filesystem
    teammate-planted-link attack class.

    Returns:
        ``{"pre_exclusion": int, "post_exclusion": int}``.
    """
    target_glob = paths_glob if paths_glob else glob
    candidates = _glob_candidates(repo_root, target_glob, workspace_roots=workspace_roots)

    pre = 0
    post = 0
    for p in candidates:
        # Refuse symlinks before is_file() (which follows symlinks):
        # a teammate-planted symlink to /etc/passwd would otherwise be
        # opened by the AST extractors. Counts as neither pre nor post.
        if os.path.islink(p):
            continue
        if not p.is_file():
            continue
        pre += 1
        try:
            rel = p.relative_to(repo_root)
        except ValueError:
            # Outside repo_root: still counts pre-exclusion (we walked it)
            # but is structurally invalid for clustering. Skip post.
            continue
        if _has_excluded_component(rel, EXCLUDE_FROM_CLUSTERING_DIRS):
            continue
        if _matches_filename_glob(p.name, EXCLUDE_FROM_CLUSTERING_FILE_GLOBS):
            continue
        if rel.as_posix() in EXCLUDE_FROM_CLUSTERING_EXACT_RELPATHS:
            continue
        post += 1
    return {"pre_exclusion": pre, "post_exclusion": post}


def discover_files(
    repo_root: Path,
    *,
    glob: str = "**/*.{ts,tsx,js,jsx,mjs,cjs}",
    paths_glob: str | None = None,
    workspace_roots: list[str] | None = None,
) -> list[Path]:
    """Discover candidate source files in a repo.

    Args:
        repo_root: absolute path to the repo root
        glob: default file glob (TS/JS variants); ignored if paths_glob given
        paths_glob: user-supplied scope override (per architecture "with globs:
                    still enforce 50k post-glob count")
        workspace_roots: v0.5.3 (Bug B) optional list of repo-relative
                    workspace dirs (e.g. ``["apps/web", "apps/api"]``).
                    When provided, the walker scans only inside those dirs
                    (avoiding the empty monorepo root + unrelated siblings).
                    Used by the orchestrator's monorepo path-down detection.

    Returns:
        List of absolute Paths, with EXCLUDE_FROM_CLUSTERING_PATTERNS already removed.
        Order: sorted lexicographically (deterministic for clustering stability).

    Raises:
        TooManyFilesError: if post-exclusion count exceeds REPO_SIZE_GUARD.
    """
    target_glob = paths_glob if paths_glob else glob
    candidates = _glob_candidates(repo_root, target_glob, workspace_roots=workspace_roots)

    # Apply path-based exclusions (component-based, not fnmatch-glob)
    filtered: list[Path] = []
    for p in candidates:
        # Refuse symlinks before is_file() (which follows them). A symlink
        # planted in the source tree would otherwise be read by the AST
        # extractors and could leak target-file content into the canonical
        # excerpt / cluster signal. Dropping them at discovery means the
        # downstream extractor never sees the path.
        if os.path.islink(p):
            continue
        if not p.is_file():
            continue
        try:
            rel = p.relative_to(repo_root)
        except ValueError:
            continue
        if _has_excluded_component(rel, EXCLUDE_FROM_CLUSTERING_DIRS):
            continue
        if _matches_filename_glob(p.name, EXCLUDE_FROM_CLUSTERING_FILE_GLOBS):
            continue
        # v0.5.2 (Bug 4): drop Rails-autogenerated snapshots that defeat
        # partial-refresh diffing. POSIX path so the comparison is stable
        # across Windows runs (unused today but cheap insurance).
        if rel.as_posix() in EXCLUDE_FROM_CLUSTERING_EXACT_RELPATHS:
            continue
        filtered.append(p)

    # Repo-size ceiling
    if len(filtered) > REPO_SIZE_GUARD:
        raise TooManyFilesError(len(filtered))

    # Deterministic order for clustering stability
    filtered.sort()
    return filtered


def is_eligible_as_canonical(rel_path: str) -> bool:
    """Return True if a file may be picked as a canonical witness.

    Files in test/, legacy/, archive/, etc. are excluded from canonical
    selection but remain eligible for clustering.
    """
    return not _matches_any(rel_path, EXCLUDE_FROM_CANONICAL_POOL_PATTERNS)


def is_likely_generated(content_first_512_bytes: str) -> bool:
    """Heuristic: True if file content starts with a generated-code marker.

    Common patterns:
    - `// Code generated by ... DO NOT EDIT.` (gRPC, protobuf, etc.)
    - `# Generated by ...` (Python codegen)
    - `/* eslint-disable */ // ... auto-generated ...`
    - `// @generated SignedSource<<...>>` (Meta tooling)

    Phase 2B keeps this minimal; Phase 4 adds .gitattributes linguist-generated=true.
    """
    head = content_first_512_bytes.lower()
    markers = (
        "code generated by",
        "do not edit",
        "@generated",
        "auto-generated",
        "autogenerated",
        "this file was generated",
        "this file is generated",
    )
    return any(m in head for m in markers)
