# CSS.

name = "css"
extensions = [".css", ".scss"]

skip_subtree_nodes = ["comment"]

[top_level_kinds]
rule_set = "RuleSet"
media_statement = "MediaStatement"
import_statement = "ImportStatement"
keyframes_statement = "KeyframesStatement"
comment = ""

[imports]
module_nodes = ["import_statement"]

[flags]
