"""Regression coverage for bootstrap discovery review fixes.

Two confirmed findings against ``chameleon_mcp.bootstrap.discovery``:

1. A symlinked DIRECTORY inside the repo that points outside it escaped the
   containment guard (the leaf file is not a symlink and the lexical relative
   path carries no ".."), so external bytes could reach the canonical pool.
2. ``is_likely_generated`` did not recognise the Django migration header
   ``# Generated by Django <ver> on <date>``, so auto-generated migrations
   could be picked as canonical witnesses.

Each symlinked-directory case uses a NON-RECURSIVE glob so the directory
symlink is descended on every CPython version (3.13 flipped ``recurse_symlinks``
to ``False`` for ``**``, which would hide the escape under the default glob and
produce a false green).
"""

from __future__ import annotations

from pathlib import Path

from chameleon_mcp.bootstrap import discovery as d


def _make_repo(tmp_path: Path) -> Path:
    repo = (tmp_path / "repo").resolve()
    repo.mkdir(parents=True, exist_ok=True)
    return repo


def _external_dir(tmp_path: Path) -> Path:
    ext = (tmp_path / "external").resolve()
    ext.mkdir(parents=True, exist_ok=True)
    (ext / "secret.ts").write_text("TOPSECRET", encoding="utf-8")
    return ext


# ---------------------------------------------------------------------------
# Finding 1: symlinked directory escapes the containment guard
# ---------------------------------------------------------------------------


def test_discover_files_drops_file_behind_dir_symlink_escaping_repo(tmp_path):
    repo = _make_repo(tmp_path)
    ext = _external_dir(tmp_path)
    # An in-repo "linked/" name that is actually a symlink to an external dir.
    (repo / "linked").symlink_to(ext, target_is_directory=True)

    got = d.discover_files(repo, paths_glob="linked/*.ts")
    # The external file behind the directory symlink must not be discovered.
    assert got == []


def test_discovery_stats_excludes_file_behind_dir_symlink_escaping_repo(tmp_path):
    repo = _make_repo(tmp_path)
    ext = _external_dir(tmp_path)
    (repo / "linked").symlink_to(ext, target_is_directory=True)

    stats = d.discovery_stats(repo, paths_glob="linked/*.ts")
    # External bytes never reach clustering, regardless of where the guard sits
    # relative to the pre-exclusion counter.
    assert stats["post_exclusion"] == 0


def test_discover_files_keeps_in_repo_file_under_resolved_root(tmp_path):
    # The containment guard resolves both sides, so a legit in-repo file is
    # kept even when the repo root itself sits under a symlinked prefix.
    repo = _make_repo(tmp_path)
    (repo / "src").mkdir(parents=True, exist_ok=True)
    (repo / "src" / "real.ts").write_text("x", encoding="utf-8")

    got = sorted(
        p.relative_to(repo).as_posix() for p in d.discover_files(repo, paths_glob="src/*.ts")
    )
    assert got == ["src/real.ts"]


# ---------------------------------------------------------------------------
# Finding 2: Django migration header is recognised as generated
# ---------------------------------------------------------------------------


def test_is_likely_generated_matches_django_migration_header():
    head = "# Generated by Django 4.2.1 on 2024-01-01 12:00\n\nfrom django.db import migrations\n"
    assert d.is_likely_generated(head) is True


def test_is_likely_generated_still_matches_code_generated_by():
    assert d.is_likely_generated("// Code generated by protoc. DO NOT EDIT.\n") is True


def test_is_likely_generated_false_on_handwritten_source():
    assert d.is_likely_generated("from app.models import Listing\n\nclass Foo:\n") is False
