"""Tier-3 duplication-reuse tasks (TS) against CHAMELEON_TEST_TS_REPO.

Neutral feature-request prompts, each with a REAL existing helper an agent might
re-implement inline. Mined + adversarially verified from ef-client. The reuse vs
re-implement outcome is the duplication-causal A/B signal."""

from __future__ import annotations

from tests.effectiveness.tasks import EffTask

TASKS = [
    EffTask(
        task_id="t3-ts-dup-money-string-to-number",
        tier="dup",
        fixture="env-ts",
        prompt="Implement amount validation and parsing for a modal popup that accepts monetary values from users, converting formatted strings like '$1,000.00' to plain numbers for business logic calculations",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-comma-integer-to-number",
        tier="dup",
        fixture="env-ts",
        prompt="Implement a numeric input field that accepts large numbers with comma thousand separators (e.g., '1,000,000'). The field should parse the formatted string into an actual numeric value for calculations and API requests.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-transform-money-value",
        tier="dup",
        fixture="env-ts",
        prompt="Add a form field for collecting a payment amount from users. The field should accept formatted currency input and convert it to a number for backend submission. Handle edge cases like empty strings and non-numeric characters gracefully.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-transform-integer-value",
        tier="dup",
        fixture="env-ts",
        prompt="Create a form field that accepts user input for a count or quantity (like number of employees or products) and transforms it to an integer for database storage, removing any formatting characters",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-validate-date",
        tier="dup",
        fixture="env-ts",
        prompt="Add date validation to a multi-step form where users can enter business creation date in common date formats. Ensure the validation rejects ambiguous or coerced inputs while accepting valid dates in multiple common formats.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-get-item-with-expiry",
        tier="dup",
        fixture="env-ts",
        prompt="Add session-based caching for temporary user data that should automatically expire after a set time period. The cache should store data persistently but become unavailable after the expiration time without manual cleanup.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-is-email-valid",
        tier="dup",
        fixture="env-ts",
        prompt="Build an email validation function that can be used in form fields to check if a user's input is a valid email address before submission. It should handle empty values and return a boolean result.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-get-minimum-commission",
        tier="dup",
        fixture="env-ts",
        prompt="Implement a commission calculation feature that uses an agreed-upon minimum commission value if provided, but falls back to a default minimum of $10,000 if not specified. The result should always be an integer.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-get-full-name",
        tier="dup",
        fixture="env-ts",
        prompt="Create a utility to format and display a user's full name in a consistent way. If a preferred name is available, use that in place of the first name. Return an empty string if either the first or last name is missing.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-titleize",
        tier="dup",
        fixture="env-ts",
        prompt="Build a dynamic form field label generator that converts database column names like 'agreed_upon_commission' into human-readable title case labels like 'Agreed Upon Commission'.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-remove-html-tags",
        tier="dup",
        fixture="env-ts",
        prompt="Add a text analysis feature to a rich text editor that counts meaningful character content (excluding HTML markup) to enforce a minimum or maximum length requirement for expert analysis content",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-is-blank",
        tier="dup",
        fixture="env-ts",
        prompt="Add a field validation rule that rejects entries containing only whitespace or being completely empty, allowing for proper empty-field detection in form submissions",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-remove-http-prefix",
        tier="dup",
        fixture="env-ts",
        prompt="Add a new listing detail view that displays website URLs in a user-friendly format by removing the protocol prefix (http:// or https://) from links before rendering them.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-file-size",
        tier="dup",
        fixture="env-ts",
        prompt="Create a file upload progress indicator that displays the current file size in human-readable format (e.g., 2.5 MB) as users select documents for credential uploads.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-suffixed-number",
        tier="dup",
        fixture="env-ts",
        prompt="Add display formatting for large numbers in the analytics dashboard. When showing metrics like view counts and subscriber numbers, render them compactly (e.g., 1200000 becomes 1.2M, 500000 becomes 500K) with consistent decimal precision.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-process-humps",
        tier="dup",
        fixture="env-ts",
        prompt="Transform incoming API data to match form schema conventions. Convert camelCase field names to snake_case throughout the data structure (handling nested objects and arrays), while preserving UUID patterns and maintaining all-uppercase constant keys unchanged.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-has-filters-raw",
        tier="dup",
        fixture="env-ts",
        prompt="Implement filter change detection for a form. Compare the current filter values against initial values, ignoring any false boolean entries and empty objects (which represent cleared checkbox selections), returning true if substantive changes exist.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-get-offer-status",
        tier="dup",
        fixture="env-ts",
        prompt="Create an offer status label for the offer details page. Implement logic that examines offer rejection state, preparation state, and buyer confirmation state to produce a human-friendly status string (e.g., 'Rejection Pending', 'Counter', 'For Approval').",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-use-previous",
        tier="dup",
        fixture="env-ts",
        prompt="Implement a component that tracks the previous scroll position to detect whether the user is scrolling up or down the page. Return the direction as -1 (up), 0 (no change), or 1 (down).",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-use-debounced-value",
        tier="dup",
        fixture="env-ts",
        prompt="Add a live search feature to a product list that waits for the user to stop typing for 500ms before making an API request. What hook pattern would you use to debounce the search input?",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-use-window-scroll",
        tier="dup",
        fixture="env-ts",
        prompt="Create a component that shows a 'back to top' button only when the user has scrolled down more than 300px. How would you track scroll position efficiently?",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-use-document-title",
        tier="dup",
        fixture="env-ts",
        prompt="Implement a page that displays a dashboard title in the browser tab. The title should show the environment (DEV/STAGING) if not production, and include the company name as a prefix.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-use-query-action",
        tier="dup",
        fixture="env-ts",
        prompt="Add a feature where clicking a listing opens a 'make offer' popup if the URL contains a ?make-offer query parameter. The query parameter should be removed from the URL after the popup opens.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
    EffTask(
        task_id="t3-ts-dup-use-background-color",
        tier="dup",
        fixture="env-ts",
        prompt="Create a fullscreen modal component that changes the page background to a dark color while open and restores the original background when closed.",
        category="duplication",
        scorers=("duplication", "convention", "verification", "cost"),
        max_turns=45,
    ),
]

DUPLICATION_TARGETS = {
    "t3-ts-dup-money-string-to-number": {
        "existing_name": "moneyStringToNumber",
        "existing_file": "src/utils/mapper.ts",
        "needle": "moneyStringToNumber",
    },
    "t3-ts-dup-comma-integer-to-number": {
        "existing_name": "commaIntegerStringToNumber",
        "existing_file": "src/utils/mapper.ts",
        "needle": "commaIntegerStringToNumber",
    },
    "t3-ts-dup-transform-money-value": {
        "existing_name": "transformMoneyValue",
        "existing_file": "src/utils/yup.ts",
        "needle": "transformMoneyValue",
    },
    "t3-ts-dup-transform-integer-value": {
        "existing_name": "transformIntegerValue",
        "existing_file": "src/utils/yup.ts",
        "needle": "transformIntegerValue",
    },
    "t3-ts-dup-validate-date": {
        "existing_name": "validateDate",
        "existing_file": "src/utils/yup.ts",
        "needle": "validateDate",
    },
    "t3-ts-dup-get-item-with-expiry": {
        "existing_name": "getItemWithExpiry",
        "existing_file": "src/utils/localStorageExpiry.ts",
        "needle": "getItemWithExpiry",
    },
    "t3-ts-dup-is-email-valid": {
        "existing_name": "isEmailValid",
        "existing_file": "src/utils/isEmailValid.ts",
        "needle": "isEmailValid",
    },
    "t3-ts-dup-get-minimum-commission": {
        "existing_name": "getMinimumCommission",
        "existing_file": "src/utils/commission.ts",
        "needle": "getMinimumCommission",
    },
    "t3-ts-dup-get-full-name": {
        "existing_name": "getFullName",
        "existing_file": "src/utils/user.ts",
        "needle": "getFullName",
    },
    "t3-ts-dup-titleize": {
        "existing_name": "titleize",
        "existing_file": "src/utils/strings.ts",
        "needle": "titleize",
    },
    "t3-ts-dup-remove-html-tags": {
        "existing_name": "removeHtmlTags",
        "existing_file": "src/utils/strings.ts",
        "needle": "removeHtmlTags",
    },
    "t3-ts-dup-is-blank": {
        "existing_name": "isBlank",
        "existing_file": "src/utils/strings.ts",
        "needle": "isBlank",
    },
    "t3-ts-dup-remove-http-prefix": {
        "existing_name": "removeHttpPrefix",
        "existing_file": "src/utils/url.ts",
        "needle": "removeHttpPrefix",
    },
    "t3-ts-dup-file-size": {
        "existing_name": "fileSize",
        "existing_file": "src/utils/numbers.ts",
        "needle": "fileSize",
    },
    "t3-ts-dup-suffixed-number": {
        "existing_name": "suffixedNumber",
        "existing_file": "src/utils/numbers.ts",
        "needle": "suffixedNumber",
    },
    "t3-ts-dup-process-humps": {
        "existing_name": "processHumps",
        "existing_file": "src/utils/humps.ts",
        "needle": "processHumps",
    },
    "t3-ts-dup-has-filters-raw": {
        "existing_name": "hasFiltersRaw",
        "existing_file": "src/utils/checkFilters.ts",
        "needle": "hasFiltersRaw",
    },
    "t3-ts-dup-get-offer-status": {
        "existing_name": "getOfferStatus",
        "existing_file": "src/components/offers/utils.ts",
        "needle": "getOfferStatus",
    },
    "t3-ts-dup-use-previous": {
        "existing_name": "usePrevious",
        "existing_file": "src/hooks/usePrevious.ts",
        "needle": "usePrevious",
    },
    "t3-ts-dup-use-debounced-value": {
        "existing_name": "useDebouncedValue",
        "existing_file": "src/hooks/useDebouncedValue.ts",
        "needle": "useDebouncedValue",
    },
    "t3-ts-dup-use-window-scroll": {
        "existing_name": "useWindowScroll",
        "existing_file": "src/hooks/useWindowScroll.tsx",
        "needle": "useWindowScroll",
    },
    "t3-ts-dup-use-document-title": {
        "existing_name": "useDocumentTitle",
        "existing_file": "src/hooks/useDocumentTitle.tsx",
        "needle": "useDocumentTitle",
    },
    "t3-ts-dup-use-query-action": {
        "existing_name": "useQueryAction",
        "existing_file": "src/hooks/useQueryAction.ts",
        "needle": "useQueryAction",
    },
    "t3-ts-dup-use-background-color": {
        "existing_name": "useBackgroundColor",
        "existing_file": "src/hooks/useBackgroundColor.ts",
        "needle": "useBackgroundColor",
    },
}
